language: 'ko-KR'
reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
    base_branches:
      - 'main'
      - 'develop'
      - 'release/*'
chat:
  auto_reply: true
