name: docs
description: Do you have documentation updates?
title: "[docs] "
labels: ["docs"]
body:
  - type: textarea
    id: docs-description
    attributes:
      label: 📄 Description
      description: Please describe the documentation updates.
      placeholder: Provide detailed description!
    validations:
      required: true
  - type: textarea
    id: docs-tasks
    attributes:
      label: ✅ Tasks
      description: Please list the tasks that need to be done.
      placeholder: Break them down as much as possible!
    validations:
      required: true
  - type: textarea
    id: docs-notes
    attributes:
      label: 📝 Notes
      description: Any additional notes?
    validations:
      required: false