name: fix
description: Do you have a bug fix?
title: "[fix] "
labels: ["fix"]
body:
  - type: textarea
    id: fix-description
    attributes:
      label: 📄 Description
      description: Please describe the bug and the fix.
      placeholder: Provide detailed description!
    validations:
      required: true
  - type: textarea
    id: fix-tasks
    attributes:
      label: ✅ Tasks
      description: Please list the tasks that need to be done.
      placeholder: Break them down as much as possible!
    validations:
      required: true
  - type: textarea
    id: fix-notes
    attributes:
      label: 📝 Notes
      description: Any additional notes?
    validations:
      required: false