name: init
description: Is this the initial setup or creation of the project?
title: "[init] "
labels: ["init"]
body:
  - type: textarea
    id: init-description
    attributes:
      label: 📄 Description
      description: Please describe the initial setup or creation.
      placeholder: Provide detailed description!
    validations:
      required: true
  - type: textarea
    id: init-tasks
    attributes:
      label: ✅ Tasks
      description: Please list the tasks that need to be done.
      placeholder: Break them down as much as possible!
    validations:
      required: true
  - type: textarea
    id: init-notes
    attributes:
      label: 📝 Notes
      description: Any additional notes?
    validations:
      required: false