name: release
description: Are you releasing or deploying the project?
title: "[release] "
labels: ["release"]
body:
  - type: textarea
    id: release-description
    attributes:
      label: 📄 Description
      description: Please describe the release or deployment.
      placeholder: Provide detailed description!
    validations:
      required: true
  - type: textarea
    id: release-tasks
    attributes:
      label: ✅ Tasks
      description: Please list the tasks that need to be done.
      placeholder: Break them down as much as possible!
    validations:
      required: true
  - type: textarea
    id: release-notes
    attributes:
      label: 📝 Notes
      description: Any additional notes?
    validations:
      required: false