name: style
description: Are you making code style changes?
title: "[style] "
labels: ["style"]
body:
  - type: textarea
    id: style-description
    attributes:
      label: 📄 Description
      description: Please describe the code style changes.
      placeholder: Provide detailed description!
    validations:
      required: true
  - type: textarea
    id: style-tasks
    attributes:
      label: ✅ Tasks
      description: Please list the tasks that need to be done.
      placeholder: Break them down as much as possible!
    validations:
      required: true
  - type: textarea
    id: style-notes
    attributes:
      label: 📝 Notes
      description: Any additional notes?
    validations:
      required: false