name: test
description: Are you adding or modifying tests?
title: "[test] "
labels: ["test"]
body:
  - type: textarea
    id: test-description
    attributes:
      label: 📄 Description
      description: Please describe the tests being added or modified.
      placeholder: Provide detailed description!
    validations:
      required: true
  - type: textarea
    id: test-tasks
    attributes:
      label: ✅ Tasks
      description: Please list the tasks that need to be done.
      placeholder: Break them down as much as possible!
    validations:
      required: true
  - type: textarea
    id: test-notes
    attributes:
      label: 📝 Notes
      description: Any additional notes?
    validations:
      required: false